// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://askrrsqpmjhnkmzwmlnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFza3Jyc3FwbWpobmttendtbG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMjk4ODcsImV4cCI6MjA3MDcwNTg4N30.pyU06yBo7LjIG8B-WPry-hDpmSQtii8U7U5vNUtiEiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});